### ISSUE TITLE
Package installation

### ISSUE THREAD

**Issue by bttgcm** [KWB-R/kwb.qmra#32]
Dear all,
I am trying to install the package via githubinstall("KWB-R/kwb.qmra") and I get the following error:

Error in read.dcf(path) : 
  Found continuation line starting '    c(person(given = ...' at begin of record.

Does anyone have an idea on how to fix this?

Thank you.

**Comment by mrustl** [comment]
This is a bug in the upstream in an older version R package "remotes" which is downloads the R package kwb.qmra from Github via: 
`remotes::install_github("kwb-r/kwb.qmra", dependencies = TRUE)`

Try installing the latest "remotes" R package from CRAN with: 
`install.packages("remotes", repos = "https://cran.rstudio.com")` and try the code above again, which should work now!

Let me know if this fixed your problem!

**Comment by bttgcm** [comment]
Dear Michael,
installation seemed successful. Thank you.
One last question, is there a documentation file available online explaining a little bit how to use it?
Thank you again.

**Comment by mrustl** [comment]
Great. You can find the documentation here: 
https://kwb-r.github.io/kwb.qmra/index.html

**Comment by bttgcm** [comment]
Thanks!
