### ISSUE TITLE
Error running dummy datasets

### ISSUE THREAD

**Issue by ellyyuyang** [KWB-R/kwb.qmra#42]
Hello,

Thanks for developing this awesome tool! I have been trying to run the following command based on your dummy data, but ran into error:

**Code:**
```config<-config_read(confDir = system.file("extdata/configs/dummy", package = "kwb.qmra"))```
```risk<-simulate_risk(config, usePoisson = TRUE, debug = TRUE)```

**Error msgs:**
**Error in `dplyr::summarise()`:**
! Problem while computing `events = n()`. _**--> I saw this prob coming from LN490 from simulate.R**_
ℹ The error occurred in group 1: repeatID = 1, TreatmentSchemeID = 1, TreatmentSchemeName = "Berlin
  (BF + Slow sand)", PathogenID = 3, PathogenName = "Campylobacter jejuni and Campylobacter coli",
  PathogenGroup = "Bacteria".
**Caused by error in `n()`:**
! could not find function "n"
Run `rlang::last_error()` to see where the error occurred.

Would be grateful if you could point out what I did wrong. Thanks!

Also, I believe I have the latest kwb.qmra downloaded (because I have the added function in 0.3.0: i.e. stats_total and stats_logreductions), but my sessionInfo says it is version kwb.qmra_0.1.1  Not sure why.

> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.2.1
Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] devtools_2.4.3 usethis_2.1.5  **kwb.qmra_0.1.1**
loaded via a namespace (and not attached):
 [1] tidyselect_1.1.2  remotes_2.4.2     purrr_0.3.4       testthat_3.1.3    colorspace_2.0-3  vctrs_0.4.1      
 [7] generics_0.1.2    htmltools_0.5.2   utf8_1.2.2        rlang_1.0.2       pkgbuild_1.3.1    later_1.3.0      
[13] pillar_1.7.0      glue_1.6.2        withr_2.5.0       DBI_1.1.2         bit64_4.0.5       sessioninfo_1.2.2
[19] lifecycle_1.0.1   plyr_1.8.7        munsell_0.5.0     gtable_0.3.0      memoise_2.0.1     tzdb_0.3.0       
[25] callr_3.7.0       EnvStats_2.7.0    fastmap_1.1.0     ps_1.6.0          httpuv_1.6.5      curl_4.3.2       
[31] parallel_4.1.2    fansi_1.0.3       Rcpp_1.0.8.3      xtable_1.8-4      readr_2.1.2       scales_1.2.0     
[37] promises_1.2.0.1  cachem_1.0.6      desc_1.4.1        pkgload_1.2.4     vroom_1.5.7       mime_0.12        
[43] fs_1.5.2          bit_4.0.4         brio_1.1.3        ggplot2_3.3.5     hms_1.1.1         digest_0.6.29    
[49] processx_3.5.3    dplyr_1.0.8       shiny_1.7.1       rprojroot_2.0.3   grid_4.1.2        cli_3.2.0        
[55] tools_4.1.2       magrittr_2.0.3    tibble_3.1.6      crayon_1.5.1      tidyr_1.2.0       pkgconfig_2.0.3  
[61] ellipsis_0.3.2    prettyunits_1.1.1 assertthat_0.2.1  rstudioapi_0.13   R6_2.5.1          sfsmisc_1.1-13   
[67] compiler_4.1.2

**Comment by ellyyuyang** [comment]
oh sorry, my bad. Too early in a morning, thought dplyr was loaded automatically by kwb.qmra. 
My issue was resolved by simply loading dplyr.

**Comment by mrustl** [comment]
Hi @ellyyuyang in your session info I can see that you are using version kwb.qmra v0.1.1 instead of v0.3.0.

Best is to download the latest stable release from our [kwb-r](https://kwb-r.r-universe.dev/ui#builds) universe as shown below: 
``` r
# Enable universe(s) by kwb-r
options(repos = c(
  kwbr = 'https://kwb-r.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))

# Install some packages
install.packages('kwb.qmra')
#> Installiere Paket nach 'C:/Users/mrustl/Documents/R/win-library/4.1'
#> (da 'lib' nicht spezifiziert)
#> package 'kwb.qmra' successfully unpacked and MD5 sums checked
#> 
#> The downloaded binary packages are in
#>  C:\Users\mrustl\AppData\Local\Temp\RtmpYxYXF9\downloaded_packages



config <-  kwb.qmra::config_read(confDir = system.file("extdata/configs/dummy", 
                                                       package = "kwb.qmra"))
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   name = col_character(),
#>   type = col_character(),
#>   value = col_double(),
#>   min = col_double(),
#>   max = col_double(),
#>   mode = col_double(),
#>   mean = col_double(),
#>   sd = col_logical(),
#>   meanlog = col_logical(),
#>   sdlog = col_logical()
#> )
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   PathogenID = col_double(),
#>   PathogenName = col_character(),
#>   PathogenGroup = col_character(),
#>   simulate = col_double(),
#>   type = col_character(),
#>   value = col_logical(),
#>   min = col_double(),
#>   max = col_double(),
#>   mode = col_logical(),
#>   mean = col_logical(),
#>   sd = col_logical(),
#>   meanlog = col_logical(),
#>   sdlog = col_logical()
#> )
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   TreatmentID = col_double(),
#>   TreatmentName = col_character(),
#>   TreatmentGroup = col_character(),
#>   PathogenGroup = col_character(),
#>   type = col_character(),
#>   value = col_logical(),
#>   min = col_double(),
#>   max = col_double(),
#>   mode = col_logical(),
#>   mean = col_logical(),
#>   sd = col_logical(),
#>   meanlog = col_logical(),
#>   sdlog = col_logical()
#> )
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   TreatmentSchemeID = col_double(),
#>   TreatmentSchemeName = col_character(),
#>   TreatmentID = col_double(),
#>   TreatmentName = col_character()
#> )
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   PathogenID = col_double(),
#>   PathogenName = col_character(),
#>   PathogenGroup = col_character(),
#>   `Best fit model*` = col_character(),
#>   k = col_double(),
#>   alpha = col_double(),
#>   N50 = col_double(),
#>   `Host type` = col_character(),
#>   `Dose units` = col_character(),
#>   Route = col_character(),
#>   Response = col_character(),
#>   Reference = col_character(),
#>   Link = col_character()
#> )
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   PathogenID = col_double(),
#>   PathogenName = col_character(),
#>   infection_to_illness = col_double(),
#>   dalys_per_case = col_double()
#> )

risk <- kwb.qmra::simulate_risk(config, 
                                usePoisson = TRUE, 
                                debug = TRUE)
#> 
#> # STEP 0: BASIC CONFIGURATION
#> 
#> Simulated 3 pathogen(s): Campylobacter jejuni and Campylobacter coli, Rotavirus, Giardia duodenalis
#> Number of random distribution repeatings: 10
#> Number of exposure events: 365
#> 
#> # STEP 1: INFLOW
#> 
#> Simulated pathogen: Campylobacter jejuni and Campylobacter coli
#> Create 10 random distribution(s): uniform (n: 365, min: 10.000000, max: 10000.000000)
#> Simulated pathogen: Rotavirus
#> Create 10 random distribution(s): uniform (n: 365, min: 10.000000, max: 10000.000000)
#> Simulated pathogen: Giardia duodenalis
#> Create 10 random distribution(s): uniform (n: 365, min: 10.000000, max: 10000.000000)
#> Providing inflow events ... ok. (0.00s) 
#> Providing inflow paras ... ok. (0.00s) 
#> 
#> # STEP 2: TREATMENT SCHEMES
#> 
#> Create 10 random distribution(s): uniform (n: 365, min: 0.200000, max: 2.000000)
#> Create 10 random distribution(s): uniform (n: 365, min: 1.000000, max: 2.000000)
#> Create 10 random distribution(s): uniform (n: 365, min: 0.100000, max: 3.400000)
#> Create 10 random distribution(s): uniform (n: 365, min: 0.200000, max: 4.400000)
#> Create 10 random distribution(s): uniform (n: 365, min: 0.400000, max: 3.300000)
#> Create 10 random distribution(s): uniform (n: 365, min: 0.000000, max: 3.500000)
#> Create 10 random distribution(s): uniform (n: 365, min: 2.000000, max: 6.000000)
#> Create 10 random distribution(s): uniform (n: 365, min: 0.300000, max: 5.000000)
#> Create 10 random distribution(s): uniform (n: 365, min: 0.250000, max: 4.000000)
#> Create 10 random distribution(s): uniform (n: 365, min: 2.000000, max: 6.000000)
#> Create 10 random distribution(s): uniform (n: 365, min: 1.000000, max: 2.000000)
#> Create 10 random distribution(s): uniform (n: 365, min: 2.100000, max: 8.300000)
#> Create 10 random distribution(s): uniform (n: 365, min: 4.000000, max: 4.000000)
#> Create 10 random distribution(s): uniform (n: 365, min: 4.000000, max: 4.000000)
#> Create 10 random distribution(s): uniform (n: 365, min: 4.000000, max: 4.000000)
#> Simulated treatment: Conventional clarification for Bacteria
#> Simulated treatment: Conventional clarification for Protozoa
#> Simulated treatment: Conventional clarification for Viruses
#> Simulated treatment: Granular high-rate filtration for Bacteria
#> Simulated treatment: Granular high-rate filtration for Protozoa
#> Simulated treatment: Granular high-rate filtration for Viruses
#> Simulated treatment: Slow sand filtration for Bacteria
#> Simulated treatment: Slow sand filtration for Protozoa
#> Simulated treatment: Slow sand filtration for Viruses
#> Simulated treatment: Bank filtration for Bacteria
#> Simulated treatment: Bank filtration for Protozoa
#> Simulated treatment: Bank filtration for Viruses
#> Simulated treatment: UV for Bacteria
#> Simulated treatment: UV for Protozoa
#> Simulated treatment: UV for Viruses
#> Simulated treatment: Conventional clarification for Bacteria
#> Simulated treatment: Conventional clarification for Protozoa
#> Simulated treatment: Conventional clarification for Viruses
#> Simulated treatment: Granular high-rate filtration for Bacteria
#> Simulated treatment: Granular high-rate filtration for Protozoa
#> Simulated treatment: Granular high-rate filtration for Viruses
#> Simulated treatment: Slow sand filtration for Bacteria
#> Simulated treatment: Slow sand filtration for Protozoa
#> Simulated treatment: Slow sand filtration for Viruses
#> Simulated treatment: Bank filtration for Bacteria
#> Simulated treatment: Bank filtration for Protozoa
#> Simulated treatment: Bank filtration for Viruses
#> Simulated treatment: UV for Bacteria
#> Simulated treatment: UV for Protozoa
#> Simulated treatment: UV for Viruses
#> Joining, by = "TreatmentID"
#> Joining, by = "TreatmentID"
#> 
#> # STEP 3: EXPOSURE
#> 
#> Simulated exposure: volume per event
#> Create 10 random distribution(s): triangle (n: 365, min: 0.500000, max: 3.000000, mode = 1.500000)
#> Joining, by = c("PathogenGroup", "eventID", "repeatID")
#> Joining, by = c("eventID", "repeatID")
#> 
#> # STEP 4: DOSE RESPONSE
#> 
#> # A tibble: 3 x 13
#>   PathogenID PathogenName   PathogenGroup `Best fit model~       k  alpha    N50
#>        <dbl> <chr>          <chr>         <chr>              <dbl>  <dbl>  <dbl>
#> 1          3 Campylobacter~ Bacteria      beta-Poisson     NA       0.144 890   
#> 2         32 Rotavirus      Viruses       beta-Poisson     NA       0.253   6.17
#> 3         36 Giardia duode~ Protozoa      exponential       0.0199 NA      NA   
#> # ... with 6 more variables: Host type <chr>, Dose units <chr>, Route <chr>,
#> #   Response <chr>, Reference <chr>, Link <chr>
#> 
#> # STEP 5: HEALTH
#> 
#> # A tibble: 3 x 4
#>   PathogenID PathogenName                      infection_to_illn~ dalys_per_case
#>        <dbl> <chr>                                          <dbl>          <dbl>
#> 1          3 Campylobacter jejuni and Campylo~               0.7          0.0046
#> 2         32 Rotavirus                                       0.03         0.014 
#> 3         36 Giardia duodenalis                              0.3          0.0015
#> Joining, by = c("PathogenID", "PathogenName")
```

<sup>Created on 2022-04-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.1.2 (2021-11-01)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  ctype    German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2022-04-20                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source                                
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.1.0)                        
#>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.1.0)                        
#>  cli           3.1.0   2021-10-27 [1] CRAN (R 4.1.1)                        
#>  colorspace    2.0-1   2021-05-04 [1] CRAN (R 4.1.0)                        
#>  crayon        1.4.2   2021-10-29 [1] CRAN (R 4.1.1)                        
#>  DBI           1.1.1   2021-01-15 [1] CRAN (R 4.1.0)                        
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.1.0)                        
#>  dplyr         1.0.7   2021-06-18 [1] CRAN (R 4.1.2)                        
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.1.0)                        
#>  EnvStats      2.4.0   2020-10-21 [1] CRAN (R 4.1.0)                        
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.0)                        
#>  fansi         0.5.0   2021-05-25 [1] CRAN (R 4.1.0)                        
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.0)                        
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.1.0)                        
#>  generics      0.1.1   2021-10-25 [1] CRAN (R 4.1.1)                        
#>  ggplot2       3.3.5   2021-06-25 [1] CRAN (R 4.1.0)                        
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.1.0)                        
#>  gtable        0.3.0   2019-03-25 [1] CRAN (R 4.1.0)                        
#>  highr         0.9     2021-04-16 [1] CRAN (R 4.1.0)                        
#>  hms           1.1.1   2021-09-26 [1] CRAN (R 4.1.2)                        
#>  htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.1.2)                        
#>  httpuv        1.6.4   2021-12-14 [1] CRAN (R 4.1.2)                        
#>  jsonlite      1.7.2   2020-12-09 [1] CRAN (R 4.1.0)                        
#>  knitr         1.33    2021-04-24 [1] CRAN (R 4.1.0)                        
#>  kwb.qmra      0.3.0   2022-04-14 [1] https://kwb-r.r-universe.dev (R 4.1.3)
#>  kwb.utils     0.9.0   2021-12-16 [1] Github (kwb-r/kwb.utils@0452c99)      
#>  later         1.3.0   2021-08-18 [1] CRAN (R 4.1.2)                        
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.1.1)                        
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.0)                        
#>  mime          0.12    2021-09-28 [1] CRAN (R 4.1.1)                        
#>  munsell       0.5.0   2018-06-12 [1] CRAN (R 4.1.0)                        
#>  pillar        1.6.4   2021-10-18 [1] CRAN (R 4.1.1)                        
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.0)                        
#>  plyr          1.8.6   2020-03-03 [1] CRAN (R 4.1.0)                        
#>  promises      1.2.0.1 2021-02-11 [1] CRAN (R 4.1.0)                        
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.0)                        
#>  R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.1)                        
#>  Rcpp          1.0.7   2021-07-07 [1] CRAN (R 4.1.0)                        
#>  readr         1.4.0   2020-10-05 [1] CRAN (R 4.1.0)                        
#>  reprex        2.0.0   2021-04-02 [1] CRAN (R 4.1.0)                        
#>  rlang         0.4.11  2021-04-30 [1] CRAN (R 4.1.0)                        
#>  rmarkdown     2.10    2021-08-06 [1] CRAN (R 4.1.0)                        
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.0)                        
#>  scales        1.1.1   2020-05-11 [1] CRAN (R 4.1.0)                        
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.1.0)                        
#>  sfsmisc       1.1-11  2021-04-12 [1] CRAN (R 4.1.0)                        
#>  shiny         1.7.1   2021-10-02 [1] CRAN (R 4.1.2)                        
#>  stringi       1.6.1   2021-05-10 [1] CRAN (R 4.1.0)                        
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.1.0)                        
#>  styler        1.4.1   2021-03-30 [1] CRAN (R 4.1.0)                        
#>  tibble        3.1.6   2021-11-07 [1] CRAN (R 4.1.2)                        
#>  tidyr         1.1.4   2021-09-27 [1] CRAN (R 4.1.2)                        
#>  tidyselect    1.1.1   2021-04-30 [1] CRAN (R 4.1.0)                        
#>  utf8          1.2.1   2021-03-12 [1] CRAN (R 4.1.0)                        
#>  vctrs         0.3.8   2021-04-29 [1] CRAN (R 4.1.0)                        
#>  withr         2.4.3   2021-11-30 [1] CRAN (R 4.1.2)                        
#>  xfun          0.23    2021-05-15 [1] CRAN (R 4.1.0)                        
#>  xtable        1.8-4   2019-04-21 [1] CRAN (R 4.1.0)                        
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.1.0)                        
#> 
#> [1] C:/Users/mrustl/Documents/R/win-library/4.1
#> [2] C:/Program Files/R/R-4.1.2/library
```

</details>

**Comment by ellyyuyang** [comment]
> Hi @ellyyuyang in your session info I can see that you are using version kwb.qmra v0.1.1 instead of v0.3.0.
> 
> Best is to download the latest stable release from our [kwb-r](https://kwb-r.r-universe.dev/ui#builds) universe as shown below:
> 
> ```r
> # Enable universe(s) by kwb-r
> options(repos = c(
>   kwbr = 'https://kwb-r.r-universe.dev',
>   CRAN = 'https://cloud.r-project.org'))
> 
> # Install some packages
> install.packages('kwb.qmra')
> #> Installiere Paket nach 'C:/Users/mrustl/Documents/R/win-library/4.1'
> #> (da 'lib' nicht spezifiziert)
> #> package 'kwb.qmra' successfully unpacked and MD5 sums checked
> #> 
> #> The downloaded binary packages are in
> #>  C:\Users\mrustl\AppData\Local\Temp\RtmpYxYXF9\downloaded_packages
> 
> 
> 
> config <-  kwb.qmra::config_read(confDir = system.file("extdata/configs/dummy", 
>                                                        package = "kwb.qmra"))
> #> 
> #> -- Column specification --------------------------------------------------------
> #> cols(
> #>   name = col_character(),
> #>   type = col_character(),
> #>   value = col_double(),
> #>   min = col_double(),
> #>   max = col_double(),
> #>   mode = col_double(),
> #>   mean = col_double(),
> #>   sd = col_logical(),
> #>   meanlog = col_logical(),
> #>   sdlog = col_logical()
> #> )
> #> 
> #> -- Column specification --------------------------------------------------------
> #> cols(
> #>   PathogenID = col_double(),
> #>   PathogenName = col_character(),
> #>   PathogenGroup = col_character(),
> #>   simulate = col_double(),
> #>   type = col_character(),
> #>   value = col_logical(),
> #>   min = col_double(),
> #>   max = col_double(),
> #>   mode = col_logical(),
> #>   mean = col_logical(),
> #>   sd = col_logical(),
> #>   meanlog = col_logical(),
> #>   sdlog = col_logical()
> #> )
> #> 
> #> -- Column specification --------------------------------------------------------
> #> cols(
> #>   TreatmentID = col_double(),
> #>   TreatmentName = col_character(),
> #>   TreatmentGroup = col_character(),
> #>   PathogenGroup = col_character(),
> #>   type = col_character(),
> #>   value = col_logical(),
> #>   min = col_double(),
> #>   max = col_double(),
> #>   mode = col_logical(),
> #>   mean = col_logical(),
> #>   sd = col_logical(),
> #>   meanlog = col_logical(),
> #>   sdlog = col_logical()
> #> )
> #> 
> #> -- Column specification --------------------------------------------------------
> #> cols(
> #>   TreatmentSchemeID = col_double(),
> #>   TreatmentSchemeName = col_character(),
> #>   TreatmentID = col_double(),
> #>   TreatmentName = col_character()
> #> )
> #> 
> #> -- Column specification --------------------------------------------------------
> #> cols(
> #>   PathogenID = col_double(),
> #>   PathogenName = col_character(),
> #>   PathogenGroup = col_character(),
> #>   `Best fit model*` = col_character(),
> #>   k = col_double(),
> #>   alpha = col_double(),
> #>   N50 = col_double(),
> #>   `Host type` = col_character(),
> #>   `Dose units` = col_character(),
> #>   Route = col_character(),
> #>   Response = col_character(),
> #>   Reference = col_character(),
> #>   Link = col_character()
> #> )
> #> 
> #> -- Column specification --------------------------------------------------------
> #> cols(
> #>   PathogenID = col_double(),
> #>   PathogenName = col_character(),
> #>   infection_to_illness = col_double(),
> #>   dalys_per_case = col_double()
> #> )
> 
> risk <- kwb.qmra::simulate_risk(config, 
>                                 usePoisson = TRUE, 
>                                 debug = TRUE)
> #> 
> #> # STEP 0: BASIC CONFIGURATION
> #> 
> #> Simulated 3 pathogen(s): Campylobacter jejuni and Campylobacter coli, Rotavirus, Giardia duodenalis
> #> Number of random distribution repeatings: 10
> #> Number of exposure events: 365
> #> 
> #> # STEP 1: INFLOW
> #> 
> #> Simulated pathogen: Campylobacter jejuni and Campylobacter coli
> #> Create 10 random distribution(s): uniform (n: 365, min: 10.000000, max: 10000.000000)
> #> Simulated pathogen: Rotavirus
> #> Create 10 random distribution(s): uniform (n: 365, min: 10.000000, max: 10000.000000)
> #> Simulated pathogen: Giardia duodenalis
> #> Create 10 random distribution(s): uniform (n: 365, min: 10.000000, max: 10000.000000)
> #> Providing inflow events ... ok. (0.00s) 
> #> Providing inflow paras ... ok. (0.00s) 
> #> 
> #> # STEP 2: TREATMENT SCHEMES
> #> 
> #> Create 10 random distribution(s): uniform (n: 365, min: 0.200000, max: 2.000000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 1.000000, max: 2.000000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 0.100000, max: 3.400000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 0.200000, max: 4.400000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 0.400000, max: 3.300000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 0.000000, max: 3.500000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 2.000000, max: 6.000000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 0.300000, max: 5.000000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 0.250000, max: 4.000000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 2.000000, max: 6.000000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 1.000000, max: 2.000000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 2.100000, max: 8.300000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 4.000000, max: 4.000000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 4.000000, max: 4.000000)
> #> Create 10 random distribution(s): uniform (n: 365, min: 4.000000, max: 4.000000)
> #> Simulated treatment: Conventional clarification for Bacteria
> #> Simulated treatment: Conventional clarification for Protozoa
> #> Simulated treatment: Conventional clarification for Viruses
> #> Simulated treatment: Granular high-rate filtration for Bacteria
> #> Simulated treatment: Granular high-rate filtration for Protozoa
> #> Simulated treatment: Granular high-rate filtration for Viruses
> #> Simulated treatment: Slow sand filtration for Bacteria
> #> Simulated treatment: Slow sand filtration for Protozoa
> #> Simulated treatment: Slow sand filtration for Viruses
> #> Simulated treatment: Bank filtration for Bacteria
> #> Simulated treatment: Bank filtration for Protozoa
> #> Simulated treatment: Bank filtration for Viruses
> #> Simulated treatment: UV for Bacteria
> #> Simulated treatment: UV for Protozoa
> #> Simulated treatment: UV for Viruses
> #> Simulated treatment: Conventional clarification for Bacteria
> #> Simulated treatment: Conventional clarification for Protozoa
> #> Simulated treatment: Conventional clarification for Viruses
> #> Simulated treatment: Granular high-rate filtration for Bacteria
> #> Simulated treatment: Granular high-rate filtration for Protozoa
> #> Simulated treatment: Granular high-rate filtration for Viruses
> #> Simulated treatment: Slow sand filtration for Bacteria
> #> Simulated treatment: Slow sand filtration for Protozoa
> #> Simulated treatment: Slow sand filtration for Viruses
> #> Simulated treatment: Bank filtration for Bacteria
> #> Simulated treatment: Bank filtration for Protozoa
> #> Simulated treatment: Bank filtration for Viruses
> #> Simulated treatment: UV for Bacteria
> #> Simulated treatment: UV for Protozoa
> #> Simulated treatment: UV for Viruses
> #> Joining, by = "TreatmentID"
> #> Joining, by = "TreatmentID"
> #> 
> #> # STEP 3: EXPOSURE
> #> 
> #> Simulated exposure: volume per event
> #> Create 10 random distribution(s): triangle (n: 365, min: 0.500000, max: 3.000000, mode = 1.500000)
> #> Joining, by = c("PathogenGroup", "eventID", "repeatID")
> #> Joining, by = c("eventID", "repeatID")
> #> 
> #> # STEP 4: DOSE RESPONSE
> #> 
> #> # A tibble: 3 x 13
> #>   PathogenID PathogenName   PathogenGroup `Best fit model~       k  alpha    N50
> #>        <dbl> <chr>          <chr>         <chr>              <dbl>  <dbl>  <dbl>
> #> 1          3 Campylobacter~ Bacteria      beta-Poisson     NA       0.144 890   
> #> 2         32 Rotavirus      Viruses       beta-Poisson     NA       0.253   6.17
> #> 3         36 Giardia duode~ Protozoa      exponential       0.0199 NA      NA   
> #> # ... with 6 more variables: Host type <chr>, Dose units <chr>, Route <chr>,
> #> #   Response <chr>, Reference <chr>, Link <chr>
> #> 
> #> # STEP 5: HEALTH
> #> 
> #> # A tibble: 3 x 4
> #>   PathogenID PathogenName                      infection_to_illn~ dalys_per_case
> #>        <dbl> <chr>                                          <dbl>          <dbl>
> #> 1          3 Campylobacter jejuni and Campylo~               0.7          0.0046
> #> 2         32 Rotavirus                                       0.03         0.014 
> #> 3         36 Giardia duodenalis                              0.3          0.0015
> #> Joining, by = c("PathogenID", "PathogenName")
> ```
> 
> Created on 2022-04-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)
> 
> Session info

Thank you so much for your detailed response! It is very helpful! 
QMRA is a very interesting field and would be beneficial to site-specific applications, and your package definitely helps the implementation of it! Thanks!

Btw, if you happen to have any webinars planned to dedicate to this R package in the future, would def benefit the field a lot. Ofc, just suggesting, no pressure at all!

Much, appreciated!

Elly
